### ISSUE TITLE
Add support for Solaris 11

### ISSUE THREAD

**Issue by tuxmea** [ghoneycutt/puppet-module-dnsclient#32]
Solaris 10 is supported.
Is this module working without any changes also on Solaris 11?

**Comment by ghoneycutt** [comment]
Hi @tuxmea 

This module works with the classic `/etc/resolv.conf`. Solaris 11 and Ubuntu 16 both use alternative ways of configuring resolvers.

https://docs.oracle.com/cd/E36784_01/html/E37473/gmowi.html

https://help.ubuntu.com/lts/serverguide/network-configuration.html#name-resolution
