### ISSUE TITLE
Request: Ability to add custom line

### ISSUE THREAD

**Issue by adrift42** [ghoneycutt/puppet-module-dnsclient#41]
It would be great to have the option to add a custom line to the resolve.conf file. Due to how a third-party application works, a particular field is required to be added but with the current setup of the file, this is not currently possible.

Something along the lines of below added to the end of the template:

<% if not @miscfields.empty? -%>
<% @miscfields.each do |miscfields| -%>
<%= miscfields %>
<% end -%>
<% end -%>

**Comment by ghoneycutt** [comment]
This will be available in 6.0.0.
